version: '3.6'

services:
  restful-booker:
    image: ankurpshah/restful-booker
    # build: ./
    ports:
      - "3001:3001"
  test-restful-booker:
    image: postman/newman
    tty: true
    volumes:
      - type: volume
        source: collection
        target: /etc/postman
        read_only: true
      - type: volume
        source: env
        target: /etc/env
        read_only: true
      - type: volume
        source: report
        target: /etc/report
    command:
      - run
      - /etc/postman/smoke.postman_collection.json
      - --environment=/etc/env/docker.postman_environment.json
      - --reporters
      - junit
      - --reporter-junit-export=/etc/report/Smoke-report.xml
  test-restful-booker-extra:
    image: ankurpshah/newman-with-htmlextra
    tty: true
    volumes:
      - type: volume
        source: collection
        target: /etc/postman
        read_only: true
      - type: volume
        source: env
        target: /etc/env
        read_only: true
      - type: volume
        source: report
        target: /etc/report
    command:
      - run
      - /etc/postman/smoke.postman_collection.json
      - --environment=/etc/env/docker.postman_environment.json
      - --reporters
      - htmlextra
      - --reporter-htmlextra-export 
      - /etc/report/smoke.html
      - --reporter-htmlextra-title 
      - "Smoke Test"
volumes:
  collection:
    read_only: true
  env:
    read_only: true
  report: