version: '3.6'

services:
  restful-booker:
    image: ankurpshah/restful-booker
    # build: ./
    ports:
      - "3001:3001"
  test-restful-booker:
    image: postman/newman
    tty: true
    volumes:
      - ./collection:/etc/postman
      - ./env:/etc/env
      - report:/etc/report
    entrypoint: /bin/sh
    command:
      # - run
      # - /etc/postman/smoke.postman_collection.json
      # - --environment=/etc/env/docker.postman_environment.json
      # - --reporters
      # - junit
      # - --reporter-junit-export=/etc/report/Smoke-report.xml
      - sleep
      - "150"
  test-restful-booker-extra:
    image: ankurpshah/newman-with-htmlextra
    tty: true
    volumes:
      - ./collection:/etc/postman
      - ./env:/etc/env
      - report:/etc/report
    entrypoint: /bin/sh
    command:
      # - run
      # - /etc/postman/smoke.postman_collection.json
      # - --environment=/etc/env/docker.postman_environment.json
      # - --reporters
      # - htmlextra
      # - --reporter-htmlextra-export 
      # - /etc/report/smoke.html
      # - --reporter-htmlextra-title 
      # - "Smoke Test"
      - sleep
      - "150"
volumes:
  report: