version: 2 # use CircleCI 2.0
jobs: # a collection of steps
  build: # runs not using Workflows must have a `build` job as entry point
    docker: # run the steps with Docker
      - image: circleci/node:12
    
    steps: # a collection of executable commands
      - checkout # check out source code to working directory
      - setup_remote_docker

      - run:
          name: Testing API
          command: |
            set -x
            docker-compose up -d
            sleep 20
            docker-compose down

      - store_test_results:
          path: ~/report/junit
      - store_artifacts:
          path: ~/report/html