version: 2 # use CircleCI 2.0
jobs: # a collection of steps
  build: # runs not using Workflows must have a `build` job as entry point
    docker: # run the steps with Docker
      - image: postman/newman
    
    steps: # a collection of executable commands
      - checkout

      - run:
          name: Run smoke test
          command: cd scripts && ./docker_smoke_local.sh
      
      - run:
          name: Run regression test
          command: cd scripts && ./docker_regression_local.sh
      
      - store_test_results:
          path: ~/report
      - store_artifacts:
          path: ~/report